databases:
  - name: petparadise-db
    databaseName: petparadise
    user: petparadise_user

services:
  - type: web
    name: petparadise-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn petparadise.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petparadise-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
